// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_xmohvSJbpSP99zmYaIni6YVHcmZLzus',
    appId: '1:149519171356:android:f2ac016a403381bb9f04d9',
    messagingSenderId: '149519171356',
    projectId: 'topprix-9a1db',
    storageBucket: 'topprix-9a1db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8GsgmaVTZTZP-sKZ3Q6moN3s6wJ7x4k8',
    appId: '1:149519171356:ios:9f0fa58a67ae9a589f04d9',
    messagingSenderId: '149519171356',
    projectId: 'topprix-9a1db',
    storageBucket: 'topprix-9a1db.firebasestorage.app',
    androidClientId: '149519171356-upgc3qt1v1s8h0a3vqngqkn7husv3pmm.apps.googleusercontent.com',
    iosClientId: '149519171356-mm040kkmkubbncrlo95f05005f1ji0k8.apps.googleusercontent.com',
    iosBundleId: 'com.kliklokal.topprix',
  );

}